gatling {
  data {
    writers = [console, file, graphite]
    graphite {
      host = "localhost"
      port = 9109
      protocol = "tcp"
      rootPathPrefix = "gatling"
      bufferSize = 8192
      writePeriod = 1
    }
  }
}